In [1]:
from datascience import *
import pandas as pd
import seaborn as sns
import numpy as np
import math

from astropy import units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord

from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [2]:
dat = Table.read_table("hip_10pc.csv", sep=',')
dat.show(10)

In [3]:
sort_dat = dat.sort(6, descending = True)

In [5]:
sort_dat.where('HIP', are.equal_to(24436))

HIP  | RAdeg | DEdeg | Vmag | Plx  | abs_mag | dist (pc) | x    | y    | z

In [24]:
SkyCoord(ra=217.449*u.degree, dec=-62.6814*u.degree, distance=1.29478*u.pc).cartesian

<CartesianRepresentation (x, y, z) in pc
    (-0.4717512, -0.36132073, -1.15037098)>

In [59]:

x = 1.29478 * math.sin(math.radians(217.449)) * math.cos(math.radians(-62.6814)) #x
y = 1.29478 * math.sin(math.radians(217.449)) * math.sin(math.radians(-62.6814)) #y
z = 1.29478 * math.cos(math.radians(217.449)) #z
x,y,z

(-0.361320726870622, 0.6994888361433491, -1.0279192326464703)

In [75]:
SkyCoord(ra=262.595*u.degree, dec=5.54912*u.degree, distance=9.98303*u.pc).cartesian

<CartesianRepresentation (x, y, z) in pc
    (-1.28060463, -9.85337706, 0.96534978)>

In [8]:
ra = 262.595
dec = 5.54912

x = 9.98303 * math.sin(math.radians(ra)) * math.cos(math.radians(dec))
y = 9.98303 * math.sin(math.radians(ra)) * math.sin(math.radians(dec))
z = 9.98303 * math.cos(math.radians(ra)) #z

x,y,z

(-9.853377064709186, -0.9572986819796229, -1.2866342273711942)

In [23]:
ra = 262.595
dec = 5.54912

x = 9.98303 * np.cos(math.radians(ra)) * np.cos(math.radians(dec))
y = 9.98303 * np.cos(math.radians(dec)) * np.sin(math.radians(ra))
z = 9.98303 * np.sin(math.radians(dec)) #z

x,y,z

(-1.2806046263905233, -9.853377064709186, 0.9653497772466627)

In [72]:
r = 6.16
theta = 35.73
phi = 56.30

x = r * math.sin(math.radians(theta)) * math.cos(math.radians(phi))
y = r * math.sin(math.radians(theta)) * math.sin(math.radians(phi))
z = r * math.cos(math.radians(theta)) #z

x,y,z

(1.9959044832534558, 2.992732521184142, 5.0005517045997605)

In [18]:
9.98303 * math.cos(262.595)

2.682154400652812

In [30]:
y = 9.98303 * math.sin(math.radians(ra)) * math.cos(math.radians(dec))

-0.9572986819796229

In [15]:
9.98303 * math.sin(math.radians(262.595)) * math.cos(math.radians(5.54912))

-9.853377064709186

In [16]:
9.98303 * math.sin(math.radians(262.595)) * math.sin(math.radians(5.54912))

-0.9572986819796229

In [9]:
x = 0
y = 0
z = 0
r = 8.98303

x = r * ((math.sin(math.degrees(5.54912))) * (math.cos(math.degrees(262.595))))
y = r * ((math.sin(math.degrees(5.54912))) * (math.sin(math.degrees(262.595))))
z = r * math.cos(math.degrees(5.54912))

x,y,z

(4.714913386755889, 2.5635576705375014, -7.203651282934123)

In [10]:
SkyCoord(ra=101.289*u.degree, dec=-16.7131*u.degree, distance=2.63706*u.pc).cartesian

<CartesianRepresentation (x, y, z) in pc
    (-0.49441824, 2.47679621, -0.75836441)>

In [11]:
x = 0
y = 0
z = 0
r = 2.63706

x = r * ((math.sin(math.degrees(-16.7131))) * (math.cos(math.degrees(101.289))))
y = r * ((math.sin(math.degrees(-16.7131))) * (math.sin(math.degrees(101.289))))
z = r * math.cos(math.degrees(-16.7131))

x,y,z

(0.9073905857294334, 1.1686374739640524, -2.1828912531265763)

In [12]:
((math.sin(math.radians(36.66))*math.cos(math.radians(63.43))*math.cos(math.radians(36.66)))/3.74**2)+((math.cos(math.radians(36.66))*math.cos(math.radians(63.43))*math.sin(math.radians(36.66)))/3.74)

0.07259816426414659

In [13]:
(((math.cos(math.radians(36.66)))**2)/3.74**2)- (((math.sin(math.radians(36.66)))**2)/3.74)

-0.04931139027673405

In [14]:
max_Vmag = max(dat.column(3))

In [15]:
min_Vmag = min(dat.column(3))

In [16]:
sort_dat.show(1)

In [17]:
max_abs_mag = max(dat.column(5))

In [18]:
min_abs_mag = min(dat.column(5))

In [19]:
max_abs_mag, min_abs_mag

(15.449014523417619, 0.5817699133200118)

In [20]:
m = sort_dat.row(0)[3]
M = sort_dat.row(0)[5]
d = sort_dat.row(0)[6]

In [21]:
m - M = 5 - 5 * math.log10(d)

SyntaxError: can't assign to operator (<ipython-input-21-819c6091134f>, line 1)

In [ ]:
m

In [ ]:
m + 5 - 5 * (math.log10(d))

In [ ]:
alpha = 128

((128-(15.4*10.4))*-1)+128

In [ ]:
M1 = 11.01 + 5 - 5 * (math.log10(1.29))

In [ ]:
M1

In [ ]:
M1 + 5 * (math.log10(1.29)) - 5

In [ ]:
M1 + 5 * (math.log10(2.29)) - 5

In [ ]:
(((12.25 * alpha / 11.01)-128)*-1)+128

In [ ]:
M1 + 5 * (math.log10(0.29)) - 5

In [ ]:
(((7.76 * alpha / 11.01)-128)*-1)+128

In [ ]:
M + 5 * (math.log10(d)) - 5

In [ ]:
### Distancia decrementa

In [ ]:
M + 5 * (math.log10(d-1)) - 5

In [ ]:
alpha_inc = (((9.1 * alpha / 11.01)-128)*-1)+128
alpha_inc

In [ ]:
### Distancia incrementa

In [ ]:
M + 5 * (math.log10(d+1)) - 5

In [ ]:
alpha_dec = (((9.5 * alpha / 11.01)-128)*-1)+128
alpha_dec

In [ ]:
sort_dat.row(0)[1], sort_dat.row(0)[2], sort_dat.row(0)[6]

In [ ]:
xyz1 = SkyCoord(ra=float(sort_dat.row(0)[1])*u.degree, dec=float(sort_dat.row(0)[2])*u.degree, distance=sort_dat.row(0)[]*u.pc).cartesian

In [ ]:
xyz2 = SkyCoord(ra=float(sort_dat.row(0)[1])*u.degree, dec=float(sort_dat.row(0)[2])*u.degree, distance=(sort_dat.row(0)[6]-1)*u.pc).cartesian

In [ ]:
xyz3 = SkyCoord(ra=float(sort_dat.row(0)[1])*u.degree, dec=float(sort_dat.row(0)[2])*u.degree, distance=(sort_dat.row(0)[6]+1)*u.pc).cartesian

In [ ]:
xyz1.y

In [ ]:
sort_dat.row(0)[6] * math.cos(math.radians(262.59462845))

In [ ]:
sort_dat.row(0)[6] * math.sin(math.radians(262.59462845)) * math.cos(math.radians(5.5491235))

In [ ]:
sort_dat.row(0)[6] * math.sin(math.radians(262.59462845)) * math.sin(math.radians(5.5491235))

In [ ]:
xyz1

In [ ]:
xyz2

In [ ]:
xyz3

In [ ]:
r = sort_dat.row(0)[6]
x = r * math.cos(math.degrees(262.59462845))
y = r * math.sin(math.degrees(262.59462845)) * math.cos(math.degrees(5.5491235))
z = r * math.sin(math.degrees(262.59462845)) * math.sin(math.degrees(5.5491235)) * -1

x,y,z

In [ ]:
2 * math.sin(2*math.pi/3) * math.cos(3*math.pi / 4)

In [ ]:
-math.sqrt(6)/2

In [ ]:
math.cos(3)

In [ ]:
math.sin(2*math.pi/3)

In [ ]:
1.29 * math.sin(math.radians(262.59462845)) * math.cos(math.radians(5.5491235))